In [1]:
import pandas as pd
import json
import yaml
from pathlib import Path

In [2]:
MAIN_FOLDER = Path('..', 'outputs_000.001')
# MAIN_FOLDER = Path('..', 'outputs')

for f in MAIN_FOLDER.iterdir():
    if f.is_dir() :
        print(f.name)

11124db87d1e098323beb5a47f3b89f1
640f7fdb711851e1c7b0fcef93acbd40
e04a2258e77fb0b2e9c91cd549dfbf56
d74d66fc6f28bef6d04c6450fd1032d0
a73b7ec6763acdcade9a0af073095627
8d3be2a32a2e9fd2b4d970852ef63937
0827b2e89ff1488eb2f2cb2a9a09e001

In [3]:
folders = [f for f in MAIN_FOLDER.iterdir() if f.is_dir() and (Path(f, 'eval_results.json')).exists() ]

params = [ yaml.safe_load( Path(f, 'parameters.yaml').read_text() )
          for f in folders ]

results = list()
for f in folders:
    content = (Path(f, 'eval_results.json')).read_text()
    p = json.loads(content)
    p['_hash_id'] = f.name
    results.append(p)

In [4]:
df = pd.merge(
    pd.DataFrame(params),
    pd.DataFrame(results),
    on='_hash_id'
)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   _hash_id                 7 non-null      object
 1   _timestamp               7 non-null      object
 2   batch_size               7 non-null      int64
 3   bf16                     7 non-null      bool
 4   dataset                  7 non-null      object
 5   eval_steps               7 non-null      int64
 6   from_pretrained          7 non-null      object
 7   generation_max_length    7 non-null      int64
 8   grad_steps               7 non-null      int64
 9   local_rank               7 non-null      int64
 10  logging_strategy         7 non-null      object
 11  lr                       7 non-null      float64
 12  max_input_length         7 non-null      int64
 13  max_steps                7 non-null      int64
 14  model_id                 7 non-null      object
 15  no_log                   7 non-null      bool
 16  optimizer_name           7 non-null      object
 17  output_rationale         7 non-null      bool
 18  parallelize              7 non-null      bool
 19  run                      7 non-null      int64
 20  student_weight           7 non-null      float64
 21  teachers_keys            7 non-null      object
 22  teachers_weights         7 non-null      object
 23  epoch                    7 non-null      float64
 24  eval_accuracy            7 non-null      float64
 25  eval_loss                7 non-null      float64
 26  eval_runtime             7 non-null      float64
 27  eval_samples_per_second  7 non-null      float64
 28  eval_steps_per_second    7 non-null      float64
 29  eval_token_accuracy      7 non-null      float64
dtypes: bool(4), float64(9), int64(8), object(9)
memory usage: 1.6+ KB

In [6]:
df[
    ['_timestamp', 'dataset', 'epoch', 'batch_size', 'grad_steps', 'lr', 'eval_accuracy', 'eval_token_accuracy', 'eval_loss']
].sort_values('_timestamp')

,_timestamp,dataset,epoch,batch_size,grad_steps,lr,eval_accuracy,eval_token_accuracy,eval_loss
2,2025-11-22T13:25:09.677978,obqa,89.748387,8,8,0.0050,0.000000,0.002954,15.270502
3,2025-11-23T23:30:32.850101,obqa,89.748387,8,8,0.0005,0.722000,0.467545,3.232439
1,2025-11-25T03:22:56.570681,arc,388.914286,8,8,0.0005,0.549356,0.684053,6.093803
4,2025-11-26T17:51:12.135111,piqa,27.778164,8,8,0.0005,0.701850,0.068618,0.804071
5,2025-11-28T01:18:24.173980,riddle,127.273349,8,8,0.0005,0.613725,0.779412,5.044083
6,2025-11-29T07:47:43.850149,bioasq,437.524590,8,8,0.0005,0.918699,0.850000,4.635220
0,2025-12-01T14:07:29.881824,pubmedqa,875.000000,8,8,0.0005,0.690000,0.850000,7.578716

In [11]:
# (
#     df[ ['dataset', 'batch_size', 'grad_steps', 'lr', 'eval_accuracy']]
#     .to_excel('outputs-000.001.xlsx', sheet_name='001', index=False)
#     # .to_csv('experimento.csv', sep=',', index=False)
# )

In [12]:
md = (df[
    ['_timestamp', 'dataset', 'epoch', 'batch_size', 'grad_steps', 'lr', 'eval_accuracy', 'eval_token_accuracy', 'eval_loss']
].sort_values('_timestamp')
.to_markdown(index=False)
)

In [13]:
print(md)

| _timestamp                 | dataset   |    epoch |   batch_size |   grad_steps |     lr |   eval_accuracy |   eval_token_accuracy |   eval_loss |
|:---------------------------|:----------|---------:|-------------:|-------------:|-------:|----------------:|----------------------:|------------:|
| 2025-11-22T13:25:09.677978 | obqa      |  89.7484 |            8 |            8 | 0.005  |        0        |            0.00295385 |   15.2705   |
| 2025-11-23T23:30:32.850101 | obqa      |  89.7484 |            8 |            8 | 0.0005 |        0.722    |            0.467545   |    3.23244  |
| 2025-11-25T03:22:56.570681 | arc       | 388.914  |            8 |            8 | 0.0005 |        0.549356 |            0.684053   |    6.0938   |
| 2025-11-26T17:51:12.135111 | piqa      |  27.7782 |            8 |            8 | 0.0005 |        0.70185  |            0.0686181  |    0.804071 |
| 2025-11-28T01:18:24.173980 | riddle    | 127.273  |            8 |            8 | 0.0005 |        0.613725 |            0.779412   |    5.04408  |
| 2025-11-29T07:47:43.850149 | bioasq    | 437.525  |            8 |            8 | 0.0005 |        0.918699 |            0.85       |    4.63522  |
| 2025-12-01T14:07:29.881824 | pubmedqa  | 875      |            8 |            8 | 0.0005 |        0.69     |            0.85       |    7.57872  |

## Tempo de execução

In [26]:
df[['_hash_id', 'dataset']]

                           _hash_id   dataset
0  11124db87d1e098323beb5a47f3b89f1  pubmedqa
1  640f7fdb711851e1c7b0fcef93acbd40       arc
2  e04a2258e77fb0b2e9c91cd549dfbf56      obqa
3  d74d66fc6f28bef6d04c6450fd1032d0      obqa
4  a73b7ec6763acdcade9a0af073095627      piqa
5  8d3be2a32a2e9fd2b4d970852ef63937    riddle
6  0827b2e89ff1488eb2f2cb2a9a09e001    bioasq

In [15]:
folders = [f for f in MAIN_FOLDER.iterdir() if f.is_dir() and (Path(f, 'train_results.json')).exists() ]

results = list()
for f in folders:
    content = (Path(f, 'train_results.json')).read_text()
    p = json.loads(content)
    p['_hash_id'] = f.name
    results.append(p)

In [16]:
results[0]

{'global_step': 7000,
 'metrics': {'epoch': 875.0,
  'total_flos': 0.0,
  'train_loss': 0.08531488909040179,
  'train_runtime': 218048.9373,
  'train_samples_per_second': 2.055,
  'train_steps_per_second': 0.032},
 'training_loss': 0.08531488909040179,
 '_hash_id': '11124db87d1e098323beb5a47f3b89f1'}

In [32]:
df_train = pd.merge(
                pd.json_normalize(results,record_prefix='metrics'),
                df[['_hash_id', 'dataset', '_timestamp']],
                on='_hash_id'
            )

df_train.columns = df_train.columns.str.replace('metrics.', '', regex=False)

In [36]:
df_train['train_runtime_hours'] = df_train['train_runtime'] / 3600

In [37]:
df_train[
    ['_timestamp', 'dataset', 'train_runtime_hours']
].sort_values('_timestamp')

                   _timestamp   dataset  train_runtime_hours
2  2025-11-22T13:25:09.677978      obqa            29.434438
3  2025-11-23T23:30:32.850101      obqa            27.719876
1  2025-11-25T03:22:56.570681       arc            38.083597
4  2025-11-26T17:51:12.135111      piqa            31.154769
5  2025-11-28T01:18:24.173980    riddle            30.280696
6  2025-11-29T07:47:43.850149    bioasq            54.251230
0  2025-12-01T14:07:29.881824  pubmedqa            60.569149

In [38]:
md = (
    df_train[
        ['_timestamp', 'dataset', 'train_runtime_hours']
    ].sort_values('_timestamp')
    .to_markdown(index=False)
)

print(md)

| _timestamp                 | dataset   |   train_runtime_hours |
|:---------------------------|:----------|----------------------:|
| 2025-11-22T13:25:09.677978 | obqa      |               29.4344 |
| 2025-11-23T23:30:32.850101 | obqa      |               27.7199 |
| 2025-11-25T03:22:56.570681 | arc       |               38.0836 |
| 2025-11-26T17:51:12.135111 | piqa      |               31.1548 |
| 2025-11-28T01:18:24.173980 | riddle    |               30.2807 |
| 2025-11-29T07:47:43.850149 | bioasq    |               54.2512 |
| 2025-12-01T14:07:29.881824 | pubmedqa  |               60.5691 |